# Aula 04 - Exercícios 

Resolva os exercícios nos campos indicados.

## Ajustes

In [ ]:
home <- path.expand("~")
lib_dir <- file.path(file.path(home, "R"), "lib")
dir.create(lib_dir, showWarnings = FALSE)

library(utils)
.libPaths(c(lib_dir, .libPaths()))

# libraries needed
install.packages("tidyverse", dependencies = TRUE)
library(tidyverse)

set.seed(42) # makes sure random numbers are reproducible

Installing package into 'C:/Users/lmarc/Documents/R/lib'
(as 'lib' is unspecified)

also installing the dependencies 'rlang', 'feather'

## Aula 04 - Exercícios

### Pipes

#### 4.1. Reescreva a sequência de comandos a seguir em um único _pipeline_

In [5]:
# do not edit this chunk
x <- 1:20 # integers from 1:20
y <- rep(x, 2) # then repeat them twice
z <- sum(y) # and then take the sum
z

[1] 420

In [6]:
#z <- sum(rep(1:20,2))
#z
z<- rep(1:20,2) %>% sum ()
z

ERROR: Error in rep(1:20, 2) %>% sum(): não foi possível encontrar a função "%>%"

#### 4.2. Desconstrua o seguinte _pipeline_ em comandos separados

In [6]:
lager <- LETTERS[c(18, 5, 7, 1, 12)] %>%
  rev() %>%
  paste(collapse = "")

lager

[1] "LAGER"

In [7]:
# Escreva aqui a resposta. A saída deve ser a mesma

### Análise de sentimento

As questões 4.3 a 4.7 apresentam algum erro. Arrume os erros nos códigos abaixo

#### 4.3. Carregue os dados de [sensation_seeking.csv](https://psyteachr.github.io/msc-data-skills/data/sensation_seeking.csv)

In [8]:
ss <- read_csv(https://psyteachr.github.io/msc-data-skills/data/sensation_seeking.csv)

Parsed with column specification:
cols(
  id = col_double(),
  user_id = col_double(),
  date = col_date(format = ""),
  sss1 = col_double(),
  sss2 = col_double(),
  sss3 = col_double(),
  sss4 = col_double(),
  sss5 = col_double(),
  sss6 = col_double(),
  sss7 = col_double(),
  sss8 = col_double(),
  sss9 = col_double(),
  sss10 = col_double(),
  sss11 = col_double(),
  sss12 = col_double(),
  sss13 = col_double(),
  sss14 = col_double()
)

In [9]:
# Coloque a resposta aqui. A saída deve ser a mesma

#### 4.4. Faça a conversão do formato largo para o formato longo

In [11]:
ss_long <- gather(ss, "question", "score")
ss_long

       id    user_id date       question score
1      3144    0     2006-05-07 sss1     1
2       133    1     2004-12-08 sss1     0
3       175    2     2005-01-14 sss1     0
4       285    5     2005-02-22 sss1     1
5         1    8     2004-09-29 sss1     1
6         3    9     2004-09-30 sss1     1
7         4   10     2004-10-01 sss1     1
8         5   17     2004-10-05 sss1     1
9         6   19     2004-10-05 sss1     1
10        7   20     2004-10-05 sss1     1
11        8   21     2004-10-06 sss1     1
12        9   22     2004-10-07 sss1     0
13       10   23     2004-10-08 sss1     0
14       12   24     2004-10-09 sss1     0
15       11   27     2004-10-09 sss1     1
16       13   30     2004-10-10 sss1     0
17       14   31     2004-10-10 sss1     1
18       15   32     2004-10-10 sss1     1
19       16   33     2004-10-10 sss1     1
20       17   34     2004-10-11 sss1     1
21       18   35     2004-10-11 sss1     0
22       19   37     2004-10-11 sss1     1
23      268   47     2005-02-18 sss1     1
24       38   51     2004-10-18 sss1     1
25       94   67     2004-11-25 sss1     1
26       20   78     2004-10-12 sss1     0
27       21   82     2004-10-12 sss1     0
28       65   84     2004-11-01 sss1     0
29      287   98     2005-02-23 sss1     0
30      200  102     2005-02-02 sss1     0
⋮      ⋮     ⋮       ⋮          ⋮        ⋮
378265 30323 527630  2016-05-10 sss14    0
378266 30325 527681  2016-05-13 sss14    0
378267 30327 527949  2016-05-21 sss14    0
378268 30328 528015  2016-05-22 sss14    0
378269 30329 528202  2016-05-27 sss14    1
378270 30330 528279  2016-05-29 sss14    0
378271 30332 528362  2016-06-01 sss14    0
378272 30333 528822  2016-06-15 sss14    0
378273 30335 528848  2016-06-17 sss14    0
378274 30334 528854  2016-06-17 sss14    0
378275 30336 528986  2016-06-22 sss14    0
378276 30337 529094  2016-06-24 sss14    0
378277 30339 529253  2016-07-01 sss14    1
378278 30340 529350  2016-07-04 sss14    1
378279 30341 529519  2016-07-08 sss14    1
378280 30342 529582  2016-07-10 sss14    0
378281 30343 529593  2016-07-10 sss14    0
378282 30344 529675  2016-07-15 sss14    1
378283 30345 529681  2016-07-16 sss14    1
378284 30346 529746  2016-07-17 sss14    0
378285 30347 530008  2016-07-29 sss14    1
378286 30348 530297  2016-08-09 sss14    0
378287 30349 530367  2016-08-13 sss14    0
378288 30350 530587  2016-08-20 sss14    1
378289 30351 530595  2016-08-20 sss14    1
378290 30352 530756  2016-08-23 sss14    0
378291 30353 530784  2016-08-24 sss14    1
378292 30354 530820  2016-08-25 sss14    1
378293 30355 530930  2016-08-30 sss14    0
378294 30356 531071  2016-09-06 sss14    0

In [12]:
# Coloque a resposta aqui. A saída deve ser a mesma

#### 4.5. Divida a coluna `question` em duas colunas: `domain` e `qnumber`

In [13]:
ss_sep <- ss_long %>%
  separate(question, domain, qnumber, sep = 3)

ss_sep

       id    user_id date       domain qnumber score
1      3144    0     2006-05-07 sss    1       1
2       133    1     2004-12-08 sss    1       0
3       175    2     2005-01-14 sss    1       0
4       285    5     2005-02-22 sss    1       1
5         1    8     2004-09-29 sss    1       1
6         3    9     2004-09-30 sss    1       1
7         4   10     2004-10-01 sss    1       1
8         5   17     2004-10-05 sss    1       1
9         6   19     2004-10-05 sss    1       1
10        7   20     2004-10-05 sss    1       1
11        8   21     2004-10-06 sss    1       1
12        9   22     2004-10-07 sss    1       0
13       10   23     2004-10-08 sss    1       0
14       12   24     2004-10-09 sss    1       0
15       11   27     2004-10-09 sss    1       1
16       13   30     2004-10-10 sss    1       0
17       14   31     2004-10-10 sss    1       1
18       15   32     2004-10-10 sss    1       1
19       16   33     2004-10-10 sss    1       1
20       17   34     2004-10-11 sss    1       1
21       18   35     2004-10-11 sss    1       0
22       19   37     2004-10-11 sss    1       1
23      268   47     2005-02-18 sss    1       1
24       38   51     2004-10-18 sss    1       1
25       94   67     2004-11-25 sss    1       1
26       20   78     2004-10-12 sss    1       0
27       21   82     2004-10-12 sss    1       0
28       65   84     2004-11-01 sss    1       0
29      287   98     2005-02-23 sss    1       0
30      200  102     2005-02-02 sss    1       0
⋮      ⋮     ⋮       ⋮          ⋮      ⋮       ⋮
378265 30323 527630  2016-05-10 sss    14      0
378266 30325 527681  2016-05-13 sss    14      0
378267 30327 527949  2016-05-21 sss    14      0
378268 30328 528015  2016-05-22 sss    14      0
378269 30329 528202  2016-05-27 sss    14      1
378270 30330 528279  2016-05-29 sss    14      0
378271 30332 528362  2016-06-01 sss    14      0
378272 30333 528822  2016-06-15 sss    14      0
378273 30335 528848  2016-06-17 sss    14      0
378274 30334 528854  2016-06-17 sss    14      0
378275 30336 528986  2016-06-22 sss    14      0
378276 30337 529094  2016-06-24 sss    14      0
378277 30339 529253  2016-07-01 sss    14      1
378278 30340 529350  2016-07-04 sss    14      1
378279 30341 529519  2016-07-08 sss    14      1
378280 30342 529582  2016-07-10 sss    14      0
378281 30343 529593  2016-07-10 sss    14      0
378282 30344 529675  2016-07-15 sss    14      1
378283 30345 529681  2016-07-16 sss    14      1
378284 30346 529746  2016-07-17 sss    14      0
378285 30347 530008  2016-07-29 sss    14      1
378286 30348 530297  2016-08-09 sss    14      0
378287 30349 530367  2016-08-13 sss    14      0
378288 30350 530587  2016-08-20 sss    14      1
378289 30351 530595  2016-08-20 sss    14      1
378290 30352 530756  2016-08-23 sss    14      0
378291 30353 530784  2016-08-24 sss    14      1
378292 30354 530820  2016-08-25 sss    14      1
378293 30355 530930  2016-08-30 sss    14      0
378294 30356 531071  2016-09-06 sss    14      0

In [14]:
# Coloque a resposta aqui. A saída deve ser a mesma

#### 4.6. Agrupe as colunas `id` e `user_id` em uma nova coluna chamada `super_id`. O formato da nova coluna deve ser "id-user_id"

In [15]:
ss_unite <- ss_sep %>%
  unite(id, user_id, "super_id", sep = "-")

ss_unite

       super_id     date       domain qnumber score
1      3144-0       2006-05-07 sss    1       1
2      133-1        2004-12-08 sss    1       0
3      175-2        2005-01-14 sss    1       0
4      285-5        2005-02-22 sss    1       1
5      1-8          2004-09-29 sss    1       1
6      3-9          2004-09-30 sss    1       1
7      4-10         2004-10-01 sss    1       1
8      5-17         2004-10-05 sss    1       1
9      6-19         2004-10-05 sss    1       1
10     7-20         2004-10-05 sss    1       1
11     8-21         2004-10-06 sss    1       1
12     9-22         2004-10-07 sss    1       0
13     10-23        2004-10-08 sss    1       0
14     12-24        2004-10-09 sss    1       0
15     11-27        2004-10-09 sss    1       1
16     13-30        2004-10-10 sss    1       0
17     14-31        2004-10-10 sss    1       1
18     15-32        2004-10-10 sss    1       1
19     16-33        2004-10-10 sss    1       1
20     17-34        2004-10-11 sss    1       1
21     18-35        2004-10-11 sss    1       0
22     19-37        2004-10-11 sss    1       1
23     268-47       2005-02-18 sss    1       1
24     38-51        2004-10-18 sss    1       1
25     94-67        2004-11-25 sss    1       1
26     20-78        2004-10-12 sss    1       0
27     21-82        2004-10-12 sss    1       0
28     65-84        2004-11-01 sss    1       0
29     287-98       2005-02-23 sss    1       0
30     200-102      2005-02-02 sss    1       0
⋮      ⋮            ⋮          ⋮      ⋮       ⋮
378265 30323-527630 2016-05-10 sss    14      0
378266 30325-527681 2016-05-13 sss    14      0
378267 30327-527949 2016-05-21 sss    14      0
378268 30328-528015 2016-05-22 sss    14      0
378269 30329-528202 2016-05-27 sss    14      1
378270 30330-528279 2016-05-29 sss    14      0
378271 30332-528362 2016-06-01 sss    14      0
378272 30333-528822 2016-06-15 sss    14      0
378273 30335-528848 2016-06-17 sss    14      0
378274 30334-528854 2016-06-17 sss    14      0
378275 30336-528986 2016-06-22 sss    14      0
378276 30337-529094 2016-06-24 sss    14      0
378277 30339-529253 2016-07-01 sss    14      1
378278 30340-529350 2016-07-04 sss    14      1
378279 30341-529519 2016-07-08 sss    14      1
378280 30342-529582 2016-07-10 sss    14      0
378281 30343-529593 2016-07-10 sss    14      0
378282 30344-529675 2016-07-15 sss    14      1
378283 30345-529681 2016-07-16 sss    14      1
378284 30346-529746 2016-07-17 sss    14      0
378285 30347-530008 2016-07-29 sss    14      1
378286 30348-530297 2016-08-09 sss    14      0
378287 30349-530367 2016-08-13 sss    14      0
378288 30350-530587 2016-08-20 sss    14      1
378289 30351-530595 2016-08-20 sss    14      1
378290 30352-530756 2016-08-23 sss    14      0
378291 30353-530784 2016-08-24 sss    14      1
378292 30354-530820 2016-08-25 sss    14      1
378293 30355-530930 2016-08-30 sss    14      0
378294 30356-531071 2016-09-06 sss    14      0

In [16]:
# Coloque a resposta aqui. A saída deve ser a mesma

#### 4.7. Faça a conversão para o formato largo

In [17]:
ss_wide <- ss_unite %>%
  spreadr(qnumber, score)

ss_wide

      super_id    date       domain 1 10 11 12 13 14 2 3 4 5 6 7 8 9
1     1-8         2004-09-29 sss    1 1  0  1  1  1  1 1 1 1 1 0 1 0
2     10-23       2004-10-08 sss    0 0  1  0  0  0  0 0 0 1 0 1 0 0
3     100-426     2004-11-25 sss    0 0  1  0  0  0  1 0 0 0 0 1 0 0
4     10000-64553 2007-01-25 sss    0 0  0  0  0  0  0 0 0 1 0 1 1 1
5     10001-64554 2007-01-25 sss    0 0  1  1  1  1  0 1 1 1 0 1 1 1
6     10002-64555 2007-01-25 sss    1 0  0  1  1  1  1 1 1 1 1 1 1 1
7     10003-62492 2007-01-25 sss    1 0  1  1  1  0  0 0 0 1 0 0 0 0
8     10004-64552 2007-01-25 sss    0 0  0  0  1  0  0 0 0 1 0 1 1 1
9     10005-64557 2007-01-25 sss    1 0  1  1  0  1  1 0 1 1 1 1 1 1
10    10006-64548 2007-01-25 sss    1 0  0  0  1  0  1 0 0 0 1 1 0 1
11    10007-64556 2007-01-25 sss    0 0  0  1  0  1  0 0 0 0 0 0 0 0
12    10008-64563 2007-01-25 sss    1 1  0  0  1  0  0 0 1 1 0 1 1 1
13    10009-64562 2007-01-25 sss    1 0  0  0  1  1  0 1 0 1 0 1 0 0
14    1001-4190   2005-09-02 sss    0 0  1  0  0  1  0 0 0 0 0 0 1 1
15    10010-64565 2007-01-25 sss    0 1  0  1  1  0  1 1 0 0 1 1 1 0
16    10011-62723 2007-01-25 sss    0 0  0  1  1  0  1 0 0 1 1 0 1 1
17    10012-64551 2007-01-25 sss    0 0  0  0  1  0  0 0 0 1 1 0 1 1
18    10013-64567 2007-01-25 sss    1 0  0  0  1  1  1 1 0 1 0 1 1 0
19    10014-64568 2007-01-25 sss    0 1  1  0  1  0  0 0 1 1 0 0 1 0
20    10015-64570 2007-01-25 sss    0 1  0  1  0  0  0 0 1 1 1 1 1 1
21    10016-64569 2007-01-25 sss    1 1  0  0  1  0  1 1 1 1 0 1 1 1
22    10017-62392 2007-01-25 sss    0 0  0  0  0  0  0 0 0 1 1 1 1 1
23    10018-64572 2007-01-25 sss    1 1  1  0  1  0  1 0 0 1 1 1 1 1
24    10019-64573 2007-01-25 sss    0 0  0  1  1  1  1 0 0 1 1 0 1 1
25    10020-64575 2007-01-25 sss    1 0  1  1  1  0  1 1 0 1 1 1 1 1
26    10021-64576 2007-01-25 sss    1 0  1  0  1  0  1 0 0 1 0 0 1 1
27    10022-60613 2007-01-25 sss    1 0  1  1  1  0  0 1 0 1 1 1 1 1
28    10023-64574 2007-01-25 sss    0 0  1  1  1  0  1 1 0 1 1 0 0 1
29    10024-64581 2007-01-25 sss    1 1  1  1  1  0  1 0 0 1 1 1 1 1
30    10025-64580 2007-01-25 sss    1 0  0  1  0  0  1 1 0 0 1 1 1 1
⋮     ⋮           ⋮          ⋮      ⋮ ⋮  ⋮  ⋮  ⋮  ⋮  ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮
26992 9971-64518  2007-01-25 sss    1 1  0  1  0  0  1 0 1 1 1 1 1 1
26993 9972-64515  2007-01-25 sss    0 0  0  0  1  1  1 1 0 1 1 1 1 0
26994 9973-64524  2007-01-25 sss    1 0  1  1  1  0  1 0 1 1 1 1 1 0
26995 9974-64526  2007-01-25 sss    1 0  0  1  1  0  0 0 0 0 1 0 1 0
26996 9975-64525  2007-01-25 sss    0 0  0  0  1  0  0 1 0 1 0 0 1 0
26997 9976-64522  2007-01-25 sss    1 0  1  0  1  0  0 0 0 0 0 1 1 0
26998 9977-64523  2007-01-25 sss    0 0  0  0  1  1  0 0 0 0 0 0 0 0
26999 9978-64528  2007-01-25 sss    0 0  1  0  0  0  0 0 0 1 0 0 1 1
27000 9979-64517  2007-01-25 sss    0 0  0  0  1  0  0 0 0 1 1 0 1 0
27001 998-4180    2005-09-01 sss    1 1  1  1  1  0  1 0 1 1 1 0 1 0
27002 9981-62290  2007-01-25 sss    1 1  0  1  1  0  1 0 1 1 1 1 1 1
27003 9982-64529  2007-01-25 sss    0 0  0  0  1  0  0 0 0 0 0 0 0 0
27004 9983-64480  2007-01-25 sss    0 0  0  0  0  1  0 0 0 0 1 0 0 0
27005 9984-64530  2007-01-25 sss    0 1  0  0  0  0  0 0 1 0 0 0 0 0
27006 9985-64534  2007-01-25 sss    0 1  1  1  0  0  1 0 1 1 1 1 0 0
27007 9986-64504  2007-01-25 sss    0 1  0  0  0  0  1 0 0 0 0 0 0 0
27008 9987-64532  2007-01-25 sss    0 0  1  0  1  0  1 0 0 1 1 0 1 1
27009 9988-64540  2007-01-25 sss    0 0  0  0  0  1  0 0 0 0 0 0 0 1
27010 9989-64537  2007-01-25 sss    0 1  1  0  1  0  1 1 1 1 1 1 1 0
27011 999-4186    2005-09-01 sss    0 1  1  1  0  1  1 0 0 0 1 0 0 1
27012 9990-64542  2007-01-25 sss    1 0  0  0  1  0  0 0 0 1 1 1 1 0
27013 9991-62373  2007-01-25 sss    0 0  1  0  1  0  1 0 0 1 0 1 1 1
27014 9992-64536  2007-01-25 sss    1 1  1  0  1  0  1 0 1 1 1 1 1 1
27015 9993-64541  2007-01-25 sss    0 0  0  1  1  0  0 1 0 1 1 0 1 0
27016 9994-64543  2007-01-25 sss    1 0  0  1  1  1  0 0 0 1 0 1 1 1
27017 9995-62745  2007-01-25 sss    1 0  1  0  0  0  1 0 0 1 1 1 0 1
27018 9996-64545  2007-01-25 sss    0 0  1  0  1  0  0 1 0 1 0 0 1 0
27019 9997-64546  2007-01-25 sss    0 0  0  0  1  0  0 0 1 0 0 0 1 1
27020 9998-64547  2007-01-25 sss    0 0  0  1  1  1  0 0 0 1 1 1 1 1
27021 9999-62329  2007-01-25 sss    1 0  0  0  1  0  1 0 0 1 1 0 1 1

In [18]:
# Coloque a resposta aqui. A saída deve ser a mesma

#### 4.8. Carregue o dataset [family_composition.csv](https://psyteachr.github.io/msc-data-skills/data/family_composition.csv). 

As colunas de `oldbro` a `twinsis` fornecem o número de vizinhos daquela idade e sexo. Transforme os dados no formato longo e crie colunas separadas para a idade do vizinho (`sibage` = old, young, twin) e sexo (`sibsex` = bro, sis).

In [19]:
# Coloque a resposta aqui. A saída deve ser a mesma

Parsed with column specification:
cols(
  user_id = col_double(),
  sex = col_character(),
  age = col_double(),
  momage = col_double(),
  dadage = col_double(),
  oldbro = col_double(),
  oldsis = col_double(),
  youngbro = col_double(),
  youngsis = col_double(),
  twinbro = col_double(),
  twinsis = col_double()
)

       user_id sex    age  momage dadage sibage sibsex n
1        8     male   38.1 25     27     old    bro    0
2       67     female 19.7 29     31     old    bro    1
3       98     female 19.4 NA     NA     old    bro    1
4      103     female 20.6 NA     NA     old    bro    2
5      164     female 20.3 24     NA     old    bro    0
6      233     female 19.3 NA     NA     old    bro    0
7      235     male   18.7 NA     NA     old    bro    0
8      253     female 19.5 24     25     old    bro    0
9      256     female 19.7 NA     NA     old    bro    1
10     271     female 24.5 21     22     old    bro    0
11     298     female 17.7 28     NA     old    bro    0
12     332     male   19.6 NA     NA     old    bro    1
13     426     male   19.2 NA     NA     old    bro    0
14     429     female 19.8 NA     NA     old    bro    1
15     434     male   18.8 NA     NA     old    bro    1
16     436     female 22.1 NA     NA     old    bro    2
17     450     female 19.2 NA     NA     old    bro    0
18     452     female 19.4 NA     NA     old    bro    1
19     474     male   49.4 26     30     old    bro    0
20     514     female 19.0 NA     NA     old    bro    0
21     624     female 19.4 27     34     old    bro    0
22     807     male   23.7 NA     NA     old    bro    0
23     881     male   32.6 24     25     old    bro    0
24     948     male   45.6 23     28     old    bro    0
25     962     female 20.3 NA     NA     old    bro    0
26     993     male   25.3 NA     NA     old    bro    0
27     994     female 15.1 NA     NA     old    bro    0
28     995     male   19.9 NA     NA     old    bro    0
29     996     female 46.8 NA     NA     old    bro    3
30     998     female 26.7 NA     NA     old    bro    1
⋮      ⋮       ⋮      ⋮    ⋮      ⋮      ⋮      ⋮      ⋮
114985 538197  male   24.6 26     27     twin   sis    0
114986 538230  male   42.8 27     32     twin   sis    0
114987 538241  female 16.1 19     20     twin   sis    0
114988 538252  female 23.9 30     28     twin   sis    0
114989 538335  female 17.7 23     25     twin   sis    0
114990 538504  female 13.7 35     41     twin   sis    0
114991 538610  female 24.8 39     NA     twin   sis    0
114992 538762  female 15.5 28     36     twin   sis    0
114993 539026  female 18.0 22     34     twin   sis    0
114994 539067  female 32.4 25     27     twin   sis    0
114995 539331  male   36.1 27     31     twin   sis    0
114996 539574  female 24.1 30     30     twin   sis    0
114997 539604  female 30.3 33     34     twin   sis    0
114998 539828  female 15.0 36     45     twin   sis    0
114999 540283  female   NA 20     20     twin   sis    0
115000 540412  female 14.0 30     34     twin   sis    0
115001 540603  female 23.2 36     36     twin   sis    0
115002 540963  female 17.2 30     41     twin   sis    0
115003 541011  male   40.5 30     35     twin   sis    0
115004 541047  male   23.5 32     42     twin   sis    0
115005 541363  male   16.4 28     34     twin   sis    0
115006 541416  female 22.6 31     32     twin   sis    0
115007 541538  female 17.1 42     34     twin   sis    0
115008 541563  female 16.6 30     30     twin   sis    0
115009 541584  female 19.7 26     27     twin   sis    0
115010 541638  female 33.7 31     39     twin   sis    0
115011 541774  female 24.6 21     19     twin   sis    0
115012 542500  male   36.1 26     26     twin   sis    0
115013 542561  male   21.0 22     23     twin   sis    0
115014 542605  female 18.7 25     29     twin   sis    0

### Descrições visuais

#### 4.9. Limpe os dados do dataset [eye_descriptions.csv](https://psyteachr.github.io/msc-data-skills/data/eye_descriptions.csv). 

O dataset contém a descrição dos olhos de 50 pessoas por 220 avaliadores (`user_id`). Alguns avaliadores escreveram mais de uma descrição por olho (máximo de 4), separado por vírgula, ponto e vírgula ou traços.

Crie um dataset com colunas serpadas para `face_id`, `description` e número da descrição (`desc_n`). Dica: para separar a string por til (\~) ou barra (/), o parâmetro `sep` deveria ser `"(~|\\/)+"`.

In [20]:
# Coloque a resposta aqui. A saída deve ser a mesma

Parsed with column specification:
cols(
  .default = col_character(),
  user_id = col_double(),
  age = col_double()
)

See spec(...) for full column specifications.

      user_id sex    age  face_id desc_n description
1     508844  male   19.0 t1      d1     empty
2     508966  female 20.4 t1      d1     bored
3     508976  female 24.8 t1      d1     Dark high on drugs
4     509196  female 14.6 t1      d1     soft brown
5     509286  female 16.7 t1      d1     brown
6     509400  male     NA t1      d1     wide
7     509503  female 36.2 t1      d1     brown tired
8     509665  female 20.7 t1      d1     far apart
9     509787  female  5.0 t1      d1     tired
10    509848  male   18.2 t1      d1     tired
11    510008  female 17.4 t1      d1     bored
12    510154  female 18.8 t1      d1     sassy tired
13    510238  male   34.5 t1      d1     unimpressed
14    510381  female 18.4 t1      d1     droopy hooded eyes
15    510527  female 14.2 t1      d1     wide
16    510617  male   15.4 t1      d1     tired
17    510715  female 19.7 t1      d1     large deep
18    510837  female 31.9 t1      d1     Tired
19    510985  female 15.0 t1      d1     Exotic
20    511103  male   60.9 t1      d1     detached
21    511104  female 18.9 t1      d1     brown
22    511230  female 17.1 t1      d1     Almond crossed
23    511346  male   16.6 t1      d1     Generic
24    511352  female 19.6 t1      d1     Slanted brown
25    511461  female 19.2 t1      d1     annoyed
26    511186  male   21.0 t1      d1     .
27    511705  female 31.1 t1      d1     sleepy
28    511842  female 27.6 t1      d1     tired but listening
29    511955  female 30.0 t1      d1     wide
30    511947  female 19.0 t1      d1     we
⋮     ⋮       ⋮      ⋮    ⋮       ⋮      ⋮
12275 511104  female 18.9 t19     d4
12276 511104  female 18.9 t20     d4
12277 511104  female 18.9 t21     d4
12278 511104  female 18.9 t22     d4
12279 511104  female 18.9 t23     d4
12280 511104  female 18.9 t25     d4
12281 511104  female 18.9 t26     d4
12282 511104  female 18.9 t27     d4
12283 511104  female 18.9 t28     d4
12284 511104  female 18.9 t29     d4
12285 511104  female 18.9 t30     d4
12286 511104  female 18.9 t31     d4
12287 511104  female 18.9 t32     d4
12288 511104  female 18.9 t33     d4
12289 511104  female 18.9 t34     d4
12290 511104  female 18.9 t35     d4
12291 511104  female 18.9 t36     d4
12292 511104  female 18.9 t37     d4
12293 511104  female 18.9 t38     d4
12294 541508  female 17.0 t39     d4      small
12295 511104  female 18.9 t40     d4
12296 511104  female 18.9 t41     d4
12297 511104  female 18.9 t42     d4
12298 511104  female 18.9 t43     d4
12299 511104  female 18.9 t44     d4
12300 511104  female 18.9 t45     d4
12301 511104  female 18.9 t47     d4
12302 511104  female 18.9 t48     d4
12303 511104  female 18.9 t49     d4
12304 511104  female 18.9 t50     d4